<Project Sdk="Microsoft.NET.Sdk">

  <!-- 공통 설정은 여기에! -->
  <PropertyGroup>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <!-- x64 확정 -->
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <!-- Debug 전용 -->
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <!-- Debug 빌드 전용 설정만! -->
    <!--<DefineConstants>DEBUG;TRACE;CUSTOM_MODE</DefineConstants>-->
    <Optimize>false</Optimize>
  </PropertyGroup>

  <!-- Release 전용 -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <!-- Release 빌드 전용 설정만! -->
    <!-- 무설치(Self-contained) -->
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <!-- EXE 하나(싱글 파일) -->
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspectCore.Extensions.DependencyInjection" Version="2.4.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes.MahApps" Version="5.2.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="ScreenRecorderLib" Version="6.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SonoCap.MES.ImageProcess\SonoCap.MES.ImageProcess.vcxproj" />
    <ProjectReference Include="..\SonoCap.MES.Services\SonoCap.MES.Services.csproj" />
    <ProjectReference Include="..\SonoCap.WpfCommons\SonoCap.WpfCommons.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="start.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
